## Fetch API

In [ ]:
import os
import requests
import pandas as pd
from dotenv import load_dotenv

load_dotenv()

base_url = os.getenv("BASE_URL")   # t.ex. https://api.swedavia.se/flightinfo/v2
api_key = os.getenv("FLIGHT_KEY")

url = f"{base_url}/ARN/arrivals/2026-10-08"
headers = {
    "Ocp-Apim-Subscription-Key": api_key,
    "Accept": "application/json",
}

response = requests.get(url, headers=headers, timeout=10)
response.raise_for_status()   

data = response.json()
df = pd.json_normalize(data["flights"])
print(df.head())

  flightId departureAirportSwedish departureAirportEnglish codeShareData  \
0   FR4464              Birmingham              Birmingham            []
1   FR3008                  Dublin                  Dublin            []
2    FR971                   Zadar                   Zadar            []
3   FR9447              Manchester              Manchester            []
4   FR6833                  Malaga                  Malaga            []

  remarksEnglish remarksSwedish viaDestinations diIndicator  \
0             []             []              []           I
1             []             []              []           I
2             []             []              []           S
3             []             []              []           I
4             []             []              []           S

  airlineOperator.iata airlineOperator.icao  ...  \
0                   FR                  RYR  ...
1                   FR                  RYR  ...
2                   FR                  RYR  ...
3                   FR                  RYR  ...
4                   FR                  RYR  ...

  flightLegIdentifier.departureAirportIcao  \
0                                     EGBB
1                                     EIDW
2                                     LDZD
3                                     EGCC
4                                     LEMG

  flightLegIdentifier.arrivalAirportIcao baggage.baggageClaimUnit  \
0                                   ESSA                      NaN
1                                   ESSA                      NaN
2                                   ESSA                      NaN
3                                   ESSA                      NaN
4                                   ESSA                      NaN

  arrivalTime.estimatedUtc arrivalTime.actualUtc locationAndStatus.gate  \
0                      NaN                   NaN                    NaN
1                      NaN                   NaN                    NaN
2                      NaN                   NaN                    NaN
3                      NaN                   NaN                    NaN
4                      NaN                   NaN                    NaN

  baggage.firstBagUtc baggage.lastBagUtc  \
0                 NaN                NaN
1                 NaN                NaN
2                 NaN                NaN
3                 NaN                NaN
4                 NaN                NaN

  flightLegIdentifier.aircraftRegistration flightLegIdentifier.ssrCode
0                                      NaN                         NaN
1                                      NaN                         NaN
2                                      NaN                         NaN
3                                      NaN                         NaN
4                                      NaN                         NaN

[5 rows x 31 columns]

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 353 entries, 0 to 352
Data columns (total 31 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   flightId                                    353 non-null    str
 1   departureAirportSwedish                     353 non-null    str
 2   departureAirportEnglish                     353 non-null    str
 3   codeShareData                               353 non-null    object
 4   remarksEnglish                              353 non-null    object
 5   remarksSwedish                              353 non-null    object
 6   viaDestinations                             353 non-null    object
 7   diIndicator                                 353 non-null    str
 8   airlineOperator.iata                        353 non-null    str
 9   airlineOperator.icao                        353 non-null    str
 10  airlineOperator.name                        353 non-null    str
 11  arrivalTime.scheduledUtc                    353 non-null    str
 12  locationAndStatus.terminal                  353 non-null    str
 13  locationAndStatus.flightLegStatus           353 non-null    str
 14  locationAndStatus.flightLegStatusSwedish    353 non-null    str
 15  locationAndStatus.flightLegStatusEnglish    353 non-null    str
 16  flightLegIdentifier.callsign                353 non-null    str
 17  flightLegIdentifier.flightId                353 non-null    str
 18  flightLegIdentifier.flightDepartureDateUtc  353 non-null    str
 19  flightLegIdentifier.departureAirportIata    353 non-null    str
 20  flightLegIdentifier.arrivalAirportIata      353 non-null    str
 21  flightLegIdentifier.departureAirportIcao    353 non-null    str
 22  flightLegIdentifier.arrivalAirportIcao      353 non-null    str
 23  baggage.baggageClaimUnit                    309 non-null    str
 24  arrivalTime.estimatedUtc                    292 non-null    str
 25  arrivalTime.actualUtc                       291 non-null    str
 26  locationAndStatus.gate                      292 non-null    str
 27  baggage.firstBagUtc                         286 non-null    str
 28  baggage.lastBagUtc                          286 non-null    str
 29  flightLegIdentifier.aircraftRegistration    291 non-null    str
 30  flightLegIdentifier.ssrCode                 294 non-null    str
dtypes: object(4), str(27)
memory usage: 159.3+ KB

In [6]:
df.isnull()

,flightId,departureAirportSwedish,departureAirportEnglish,codeShareData,remarksEnglish,remarksSwedish,viaDestinations,diIndicator,airlineOperator.iata,airlineOperator.icao,...,flightLegIdentifier.departureAirportIcao,flightLegIdentifier.arrivalAirportIcao,baggage.baggageClaimUnit,arrivalTime.estimatedUtc,arrivalTime.actualUtc,locationAndStatus.gate,baggage.firstBagUtc,baggage.lastBagUtc,flightLegIdentifier.aircraftRegistration,flightLegIdentifier.ssrCode
0,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
349,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
350,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
351,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
352,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
df.head()

,flightId,departureAirportSwedish,departureAirportEnglish,codeShareData,remarksEnglish,remarksSwedish,viaDestinations,diIndicator,airlineOperator.iata,airlineOperator.icao,...,flightLegIdentifier.departureAirportIcao,flightLegIdentifier.arrivalAirportIcao,baggage.baggageClaimUnit,arrivalTime.estimatedUtc,arrivalTime.actualUtc,locationAndStatus.gate,baggage.firstBagUtc,baggage.lastBagUtc,flightLegIdentifier.aircraftRegistration,flightLegIdentifier.ssrCode
0,FR4464,Birmingham,Birmingham,[],[],[],[],I,FR,RYR,...,EGBB,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FR3008,Dublin,Dublin,[],[],[],[],I,FR,RYR,...,EIDW,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FR971,Zadar,Zadar,[],[],[],[],S,FR,RYR,...,LDZD,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FR9447,Manchester,Manchester,[],[],[],[],I,FR,RYR,...,EGCC,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FR6833,Malaga,Malaga,[],[],[],[],S,FR,RYR,...,LEMG,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df.columns

Index(['flightId', 'departureAirportSwedish', 'departureAirportEnglish',
       'codeShareData', 'remarksEnglish', 'remarksSwedish', 'viaDestinations',
       'diIndicator', 'airlineOperator.iata', 'airlineOperator.icao',
       'airlineOperator.name', 'arrivalTime.scheduledUtc',
       'locationAndStatus.terminal', 'locationAndStatus.flightLegStatus',
       'locationAndStatus.flightLegStatusSwedish',
       'locationAndStatus.flightLegStatusEnglish',
       'flightLegIdentifier.callsign', 'flightLegIdentifier.flightId',
       'flightLegIdentifier.flightDepartureDateUtc',
       'flightLegIdentifier.departureAirportIata',
       'flightLegIdentifier.arrivalAirportIata',
       'flightLegIdentifier.departureAirportIcao',
       'flightLegIdentifier.arrivalAirportIcao', 'baggage.baggageClaimUnit',
       'arrivalTime.estimatedUtc', 'arrivalTime.actualUtc',
       'locationAndStatus.gate', 'baggage.firstBagUtc', 'baggage.lastBagUtc',
       'flightLegIdentifier.aircraftRegistration',
       'flightLegIdentifier.ssrCode'],
      dtype='str')

In [15]:
df.dtypes

flightId                                         str
departureAirportSwedish                          str
departureAirportEnglish                          str
codeShareData                                 object
remarksEnglish                                object
remarksSwedish                                object
viaDestinations                               object
diIndicator                                      str
airlineOperator.iata                             str
airlineOperator.icao                             str
airlineOperator.name                             str
arrivalTime.scheduledUtc                         str
locationAndStatus.terminal                       str
locationAndStatus.flightLegStatus                str
locationAndStatus.flightLegStatusSwedish         str
locationAndStatus.flightLegStatusEnglish         str
flightLegIdentifier.callsign                     str
flightLegIdentifier.flightId                     str
flightLegIdentifier.flightDepartureDateUtc       str
flightLegIdentifier.departureAirportIata         str
flightLegIdentifier.arrivalAirportIata           str
flightLegIdentifier.departureAirportIcao         str
flightLegIdentifier.arrivalAirportIcao           str
baggage.baggageClaimUnit                         str
arrivalTime.estimatedUtc                         str
arrivalTime.actualUtc                            str
locationAndStatus.gate                           str
baggage.firstBagUtc                              str
baggage.lastBagUtc                               str
flightLegIdentifier.aircraftRegistration         str
flightLegIdentifier.ssrCode                      str
dtype: object

In [27]:
df['locationAndStatus.flightLegStatus'].value_counts()

locationAndStatus.flightLegStatus
LAN    291
DEL     56
CAN      6
Name: count, dtype: int64

In [28]:
df['locationAndStatus.flightLegStatusEnglish'].value_counts()

locationAndStatus.flightLegStatusEnglish
Deleted         56
Cancelled        6
Landed 23:52     2
Landed 00:02     2
Landed 16:41     2
                ..
Landed 20:37     1
Landed 21:24     1
Landed 20:55     1
Landed 22:45     1
Landed 16:38     1
Name: count, Length: 289, dtype: int64

In [26]:
df['locationAndStatus.flightLegStatusSwedish'].value_counts()

locationAndStatus.flightLegStatusSwedish
Borttagen       56
Inställd         6
Landat 23:52     2
Landat 00:02     2
Landat 16:41     2
                ..
Landat 20:37     1
Landat 21:24     1
Landat 20:55     1
Landat 22:45     1
Landat 16:38     1
Name: count, Length: 289, dtype: int64