## Fetch API

## Arrials :

In [1]:
import os
import requests
import pandas as pd
from dotenv import load_dotenv

load_dotenv()

base_url = os.getenv("BASE_URL")   # t.ex. https://api.swedavia.se/flightinfo/v2
api_key = os.getenv("FLIGHT_KEY")

url = f"{base_url}/ARN/arrivals/2026-10-08"
headers = {
    "Ocp-Apim-Subscription-Key": api_key,
    "Accept": "application/json",
}

response = requests.get(url, headers=headers, timeout=10)
response.raise_for_status()   

data = response.json()
df = pd.json_normalize(data["flights"])
print(df.head())

  flightId departureAirportSwedish departureAirportEnglish codeShareData  \
0   FR4464              Birmingham              Birmingham            []
1   FR3008                  Dublin                  Dublin            []
2    FR971                   Zadar                   Zadar            []
3   FR9447              Manchester              Manchester            []
4   FR6833                  Malaga                  Malaga            []

  remarksEnglish remarksSwedish viaDestinations diIndicator  \
0             []             []              []           I
1             []             []              []           I
2             []             []              []           S
3             []             []              []           I
4             []             []              []           S

  airlineOperator.iata airlineOperator.icao  ...  \
0                   FR                  RYR  ...
1                   FR                  RYR  ...
2                   FR                  RYR  ...
3                   FR                  RYR  ...
4                   FR                  RYR  ...

  flightLegIdentifier.departureAirportIcao  \
0                                     EGBB
1                                     EIDW
2                                     LDZD
3                                     EGCC
4                                     LEMG

  flightLegIdentifier.arrivalAirportIcao baggage.baggageClaimUnit  \
0                                   ESSA                      NaN
1                                   ESSA                      NaN
2                                   ESSA                      NaN
3                                   ESSA                      NaN
4                                   ESSA                      NaN

  arrivalTime.estimatedUtc arrivalTime.actualUtc locationAndStatus.gate  \
0                      NaN                   NaN                    NaN
1                      NaN                   NaN                    NaN
2                      NaN                   NaN                    NaN
3                      NaN                   NaN                    NaN
4                      NaN                   NaN                    NaN

  baggage.firstBagUtc baggage.lastBagUtc  \
0                 NaN                NaN
1                 NaN                NaN
2                 NaN                NaN
3                 NaN                NaN
4                 NaN                NaN

  flightLegIdentifier.aircraftRegistration flightLegIdentifier.ssrCode
0                                      NaN                         NaN
1                                      NaN                         NaN
2                                      NaN                         NaN
3                                      NaN                         NaN
4                                      NaN                         NaN

[5 rows x 31 columns]

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 353 entries, 0 to 352
Data columns (total 31 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   flightId                                    353 non-null    str
 1   departureAirportSwedish                     353 non-null    str
 2   departureAirportEnglish                     353 non-null    str
 3   codeShareData                               353 non-null    object
 4   remarksEnglish                              353 non-null    object
 5   remarksSwedish                              353 non-null    object
 6   viaDestinations                             353 non-null    object
 7   diIndicator                                 353 non-null    str
 8   airlineOperator.iata                        353 non-null    str
 9   airlineOperator.icao                        353 non-null    str
 10  airlineOperator.name                        353 non-null    str
 11  arrivalTime.scheduledUtc                    353 non-null    str
 12  locationAndStatus.terminal                  353 non-null    str
 13  locationAndStatus.flightLegStatus           353 non-null    str
 14  locationAndStatus.flightLegStatusSwedish    353 non-null    str
 15  locationAndStatus.flightLegStatusEnglish    353 non-null    str
 16  flightLegIdentifier.callsign                353 non-null    str
 17  flightLegIdentifier.flightId                353 non-null    str
 18  flightLegIdentifier.flightDepartureDateUtc  353 non-null    str
 19  flightLegIdentifier.departureAirportIata    353 non-null    str
 20  flightLegIdentifier.arrivalAirportIata      353 non-null    str
 21  flightLegIdentifier.departureAirportIcao    353 non-null    str
 22  flightLegIdentifier.arrivalAirportIcao      353 non-null    str
 23  baggage.baggageClaimUnit                    309 non-null    str
 24  arrivalTime.estimatedUtc                    292 non-null    str
 25  arrivalTime.actualUtc                       291 non-null    str
 26  locationAndStatus.gate                      292 non-null    str
 27  baggage.firstBagUtc                         286 non-null    str
 28  baggage.lastBagUtc                          286 non-null    str
 29  flightLegIdentifier.aircraftRegistration    291 non-null    str
 30  flightLegIdentifier.ssrCode                 294 non-null    str
dtypes: object(4), str(27)
memory usage: 159.3+ KB

In [3]:
df.isnull()

,flightId,departureAirportSwedish,departureAirportEnglish,codeShareData,remarksEnglish,remarksSwedish,viaDestinations,diIndicator,airlineOperator.iata,airlineOperator.icao,...,flightLegIdentifier.departureAirportIcao,flightLegIdentifier.arrivalAirportIcao,baggage.baggageClaimUnit,arrivalTime.estimatedUtc,arrivalTime.actualUtc,locationAndStatus.gate,baggage.firstBagUtc,baggage.lastBagUtc,flightLegIdentifier.aircraftRegistration,flightLegIdentifier.ssrCode
0,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
349,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
350,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
351,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
352,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [4]:
df.head()

,flightId,departureAirportSwedish,departureAirportEnglish,codeShareData,remarksEnglish,remarksSwedish,viaDestinations,diIndicator,airlineOperator.iata,airlineOperator.icao,...,flightLegIdentifier.departureAirportIcao,flightLegIdentifier.arrivalAirportIcao,baggage.baggageClaimUnit,arrivalTime.estimatedUtc,arrivalTime.actualUtc,locationAndStatus.gate,baggage.firstBagUtc,baggage.lastBagUtc,flightLegIdentifier.aircraftRegistration,flightLegIdentifier.ssrCode
0,FR4464,Birmingham,Birmingham,[],[],[],[],I,FR,RYR,...,EGBB,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FR3008,Dublin,Dublin,[],[],[],[],I,FR,RYR,...,EIDW,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FR971,Zadar,Zadar,[],[],[],[],S,FR,RYR,...,LDZD,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FR9447,Manchester,Manchester,[],[],[],[],I,FR,RYR,...,EGCC,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FR6833,Malaga,Malaga,[],[],[],[],S,FR,RYR,...,LEMG,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.columns

Index(['flightId', 'departureAirportSwedish', 'departureAirportEnglish',
       'codeShareData', 'remarksEnglish', 'remarksSwedish', 'viaDestinations',
       'diIndicator', 'airlineOperator.iata', 'airlineOperator.icao',
       'airlineOperator.name', 'arrivalTime.scheduledUtc',
       'locationAndStatus.terminal', 'locationAndStatus.flightLegStatus',
       'locationAndStatus.flightLegStatusSwedish',
       'locationAndStatus.flightLegStatusEnglish',
       'flightLegIdentifier.callsign', 'flightLegIdentifier.flightId',
       'flightLegIdentifier.flightDepartureDateUtc',
       'flightLegIdentifier.departureAirportIata',
       'flightLegIdentifier.arrivalAirportIata',
       'flightLegIdentifier.departureAirportIcao',
       'flightLegIdentifier.arrivalAirportIcao', 'baggage.baggageClaimUnit',
       'arrivalTime.estimatedUtc', 'arrivalTime.actualUtc',
       'locationAndStatus.gate', 'baggage.firstBagUtc', 'baggage.lastBagUtc',
       'flightLegIdentifier.aircraftRegistration',
       'flightLegIdentifier.ssrCode'],
      dtype='str')

In [6]:
df.dtypes

flightId                                         str
departureAirportSwedish                          str
departureAirportEnglish                          str
codeShareData                                 object
remarksEnglish                                object
remarksSwedish                                object
viaDestinations                               object
diIndicator                                      str
airlineOperator.iata                             str
airlineOperator.icao                             str
airlineOperator.name                             str
arrivalTime.scheduledUtc                         str
locationAndStatus.terminal                       str
locationAndStatus.flightLegStatus                str
locationAndStatus.flightLegStatusSwedish         str
locationAndStatus.flightLegStatusEnglish         str
flightLegIdentifier.callsign                     str
flightLegIdentifier.flightId                     str
flightLegIdentifier.flightDepartureDateUtc       str
flightLegIdentifier.departureAirportIata         str
flightLegIdentifier.arrivalAirportIata           str
flightLegIdentifier.departureAirportIcao         str
flightLegIdentifier.arrivalAirportIcao           str
baggage.baggageClaimUnit                         str
arrivalTime.estimatedUtc                         str
arrivalTime.actualUtc                            str
locationAndStatus.gate                           str
baggage.firstBagUtc                              str
baggage.lastBagUtc                               str
flightLegIdentifier.aircraftRegistration         str
flightLegIdentifier.ssrCode                      str
dtype: object

In [7]:
df['locationAndStatus.flightLegStatus'].value_counts()

locationAndStatus.flightLegStatus
LAN    291
DEL     56
CAN      6
Name: count, dtype: int64

In [8]:
df['locationAndStatus.flightLegStatusEnglish'].value_counts()

locationAndStatus.flightLegStatusEnglish
Deleted         56
Cancelled        6
Landed 23:52     2
Landed 00:02     2
Landed 16:41     2
                ..
Landed 21:24     1
Landed 16:38     1
Landed 22:45     1
Landed 20:55     1
Landed 23:19     1
Name: count, Length: 289, dtype: int64

In [9]:
df['locationAndStatus.flightLegStatusSwedish'].value_counts()

locationAndStatus.flightLegStatusSwedish
Borttagen       56
Inställd         6
Landat 23:52     2
Landat 00:02     2
Landat 16:41     2
                ..
Landat 21:24     1
Landat 16:38     1
Landat 22:45     1
Landat 20:55     1
Landat 23:19     1
Name: count, Length: 289, dtype: int64

## Function for airports (svedavia) & Dates as Parameters

In [10]:
# 1. Get BASE_URL & API KEY from dotenv file 
BASE_URL = os.getenv("BASE_URL")
API_KEY = os.getenv("FLIGHT_KEY")

In [11]:
# 2. Create an array with the Svedavia Airports 
SWE_AIRPORTS = {
    "ARN": "Stockholm Arlanda Airport",
    "BMA": "Bromma Stockholm Airport",
    "GOT": "Göteborg Landvetter Airport",
    "MMX": "Malmö Airport",
    "LLA": "Luleå Airport",
    "UME": "Umeå Airport",
    "OSD": "Åre Östersund Airport",
    "VBY": "Visby Airport",
    "RNB": "Ronneby Airport",
    "KRN": "Kiruna Airport",
}

**Source used:** https://www.geeksforgeeks.org/python/get-yesterdays-date-using-python/

In [41]:
# 3. Create a parameter for the dates to fetch 

# Import date and timedelta class
# from datetime module
from datetime import date
from datetime import timedelta

# Array with the days [today -1, today-2, today-3] 
DATES = [date.today(), date.today() - timedelta(days=1), date.today() -
         timedelta(days=2)]

#print the first day in the array (yesterday)
print(DATES[0])


# print all the dates 
for date in DATES:
    print(date)

2026-10-09
2026-10-09
2026-10-08
2026-10-07

In [51]:
# 5. Create a header - request - response 
# 6. Loop 
# For each AIRPORT 
# For each DATE

def get_flight_data(direction):
    # Empty list to store the flights in 
    all_flights = []

    headers = {
        "Ocp-Apim-Subscription-Key": API_KEY,
        "Accept": "application/json",
    }
    for airport in SWE_AIRPORTS: 
        for date in DATES: 
            url = f"{BASE_URL}/{airport}/{direction}/{date}"
            response = requests.get(url, headers=headers)
            response.raise_for_status()
            for flight in response.json()["flights"]:
                all_flights.append({**flight, "Swedavia_airport_name": airport, "Date_fetched": str(date)}) # adderade datum för det hämtade datumet också för att få in det i DF 
    return all_flights

In [52]:
# 7. Print results 

df_arrivals = pd.json_normalize(get_flight_data("arrivals"), sep="_")

In [53]:
df_departures = pd.json_normalize(get_flight_data("departures"), sep="_")

In [54]:
df_arrivals

,flightId,departureAirportSwedish,departureAirportEnglish,codeShareData,remarksEnglish,remarksSwedish,viaDestinations,diIndicator,Swedavia_airport_name,Date_fetched,...,flightLegIdentifier_arrivalAirportIcao,baggage_baggageClaimUnit,flightLegIdentifier_aircraftRegistration,arrivalTime_estimatedUtc,arrivalTime_actualUtc,locationAndStatus_gate,baggage_firstBagUtc,baggage_lastBagUtc,flightLegIdentifier_ssrCode,baggage_estimatedFirstBagUtc
0,TO7440,Paris ORY,Paris ORY,[],[],[],[],S,ARN,2026-10-09,...,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FR4464,Birmingham,Birmingham,[],[],[],[],I,ARN,2026-10-09,...,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FR317,Porto,Porto,[],[],[],[],S,ARN,2026-10-09,...,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FR3008,Dublin,Dublin,[],[],[],[],I,ARN,2026-10-09,...,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FR7686,Brindisi,Brindisi,[],[],[],[],S,ARN,2026-10-09,...,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1585,SK1042,Stockholm ARN,Stockholm ARN,"[EY3913, KL8500, LO5407]","[{'text': 'Landed 13:30', 'indicator': 'NEUTRA...","[{'text': 'Landat 13:30', 'indicator': 'NEUTRA...",[],D,KRN,2026-10-09,...,ESNQ,1,LNRGN,2026-10-09T11:26:00Z,2026-10-09T11:30:00Z,01,2026-10-09T11:40:47Z,2026-10-09T11:49:54Z,NaN,NaN
1586,SK1042,Stockholm ARN,Stockholm ARN,"[BT6158, KL8500, LO5407, NH6338]","[{'text': 'Landed 13:15', 'indicator': 'NEUTRA...","[{'text': 'Landat 13:15', 'indicator': 'NEUTRA...",[],D,KRN,2026-10-08,...,ESNQ,1,SEROM,2026-10-08T11:14:00Z,2026-10-08T11:15:00Z,01,2026-10-08T11:29:55Z,2026-10-08T11:33:17Z,NaN,NaN
1587,SK1044,Stockholm ARN,Stockholm ARN,"[EY3911, KL8502]","[{'text': 'Landed 20:27', 'indicator': 'NEUTRA...","[{'text': 'Landat 20:27', 'indicator': 'NEUTRA...",[],D,KRN,2026-10-08,...,ESNQ,1,LNRGN,2026-10-08T18:27:00Z,2026-10-08T18:27:00Z,01,2026-10-08T18:40:57Z,2026-10-08T18:45:28Z,NaN,NaN
1588,SK1042,Stockholm ARN,Stockholm ARN,"[EY3913, KL8500, LO5407]","[{'text': 'Landed 13:22', 'indicator': 'NEUTRA...","[{'text': 'Landat 13:22', 'indicator': 'NEUTRA...",[],D,KRN,2026-10-07,...,ESNQ,1,SEROE,2026-10-07T11:21:00Z,2026-10-07T11:22:00Z,01,2026-10-07T11:37:01Z,2026-10-07T11:47:41Z,NaN,NaN
1589,SK1044,Stockholm ARN,Stockholm ARN,"[EY3911, KL8502]","[{'text': 'Landed 20:45', 'indicator': 'NEUTRA...","[{'text': 'Landat 20:45', 'indicator': 'NEUTRA...",[],D,KRN,2026-10-07,...,ESNQ,1,EISCB,2026-10-07T18:40:00Z,2026-10-07T18:45:00Z,01,2026-10-07T18:54:11Z,2026-10-07T19:01:43Z,NaN,NaN

In [46]:
df_departures

,flightId,arrivalAirportSwedish,arrivalAirportEnglish,codeShareData,viaDestinations,remarksEnglish,remarksSwedish,diIndicator,airport_iata,airlineOperator_iata,...,locationAndStatus_gateAction,locationAndStatus_gateActionSwedish,locationAndStatus_gateActionEnglish,locationAndStatus_gateOpenUtc,locationAndStatus_gateCloseUtc,checkIn_checkInStatus,checkIn_checkInStatusSwedish,checkIn_checkInStatusEnglish,flightLegIdentifier_ssrCode,departureTime_estimatedUtc
0,TO7441,Paris ORY,Paris ORY,[],[],[],[],S,ARN,TO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FR7685,Brindisi,Brindisi,[],[],[],[],S,ARN,FR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FR4465,Birmingham,Birmingham,[],[],[],[],I,ARN,FR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FR316,Porto,Porto,[],[],[],[],S,ARN,FR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FR3009,Dublin,Dublin,[],[],[],[],I,ARN,FR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1576,SK1045,Stockholm ARN,Stockholm ARN,"[AF4892, BT6195, EY3989, KL8485, LO5438]",[],"[{'text': 'Delayed until 13:55', 'indicator': ...","[{'text': 'Försenad till 13:55', 'indicator': ...",D,KRN,SK,...,C,Utgång stängd,Gate closed,2026-10-09T11:16:22Z,2026-10-09T12:02:11Z,NaN,NaN,NaN,NaN,2026-10-09T11:55:00Z
1577,SK1045,Stockholm ARN,Stockholm ARN,"[AF4892, BT6195, EY3989, KL8485, LO5438]",[],"[{'text': 'Departed 13:57', 'indicator': 'NEUT...","[{'text': 'Startat 13:57', 'indicator': 'NEUTR...",D,KRN,SK,...,C,Utgång stängd,Gate closed,NaN,2026-10-08T11:53:46Z,C,Stängd,Closed,NaN,NaN
1578,SK1047,Stockholm ARN,Stockholm ARN,[EY3991],[],"[{'text': 'Departed 21:25', 'indicator': 'NEUT...","[{'text': 'Startat 21:25', 'indicator': 'NEUTR...",D,KRN,SK,...,C,Utgång stängd,Gate closed,NaN,2026-10-08T18:55:41Z,C,Stängd,Closed,NaN,NaN
1579,SK1045,Stockholm ARN,Stockholm ARN,"[AF4892, BT6195, EY3989, KL8485, LO5438]",[],"[{'text': 'Departed 14:04', 'indicator': 'NEUT...","[{'text': 'Startat 14:04', 'indicator': 'NEUTR...",D,KRN,SK,...,I,NaN,NaN,2026-10-07T11:30:19Z,2026-10-07T11:44:18Z,C,Stängd,Closed,NaN,NaN
1580,SK1047,Stockholm ARN,Stockholm ARN,[NH6339],[],"[{'text': 'Departed 21:26', 'indicator': 'NEUT...","[{'text': 'Startat 21:26', 'indicator': 'NEUTR...",D,KRN,SK,...,B,NaN,NaN,2026-10-07T18:42:50Z,2026-10-07T19:07:38Z,C,Stängd,Closed,NaN,NaN